[workspace]
authors = ["IsacPasianotto <yh4mop12z@gmail.com>"]
channels = ["conda-forge"]
name = "greppy"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.11,<3.13"
rich = ">=14.0.0,<15"
scalene = ">=1.5.41,<2"
